apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-dev
  labels:
    app: nextjs
    stage: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextjs
      stage: dev
  template:
    metadata:
      labels:
        app: nextjs
        stage: dev
    spec:
      containers:
        - name: nextjs
          image: nextjs-app:dev
          ports:
            - containerPort: 3000
            
          env:
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: DATABASE_URL_DEV
